### ISSUE TITLE
Set Facebook App ID as optional

### ISSUE THREAD

**Issue by wilderamorim** [robsonvleite/optimizer#4]
Not always when we are developing a website it has an App ID and even in production can happen not to have.

So I suggest you leave fb: app_id receive null value, so we do not have to leave a random value like 9999999999999999 to print

`<meta property="fb:app_id" content="9999999999999999"/>`

both in development and in production if that's the case, because if I do not set a value for Facebook App ID it causes me the following error:

_Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\project-folder\vendor\coffeecode\optimizer\src\Optimizer.php on line 134_

**Comment by machadomatt** [comment]
> Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\project-folder\vendor\coffeecode\optimizer\src\Optimizer.php on line 134

Actually, this occurs because the Facebook function isn't checking the $admins argument for an array and its values before iterate.

Optimizer.php class file with fixes:

```
public function facebook(string $appId = null, array $admins = null): Optimizer
    {
        if ($appId) {
            $fb = $this->meta->addChild("meta");
            $fb->addAttribute("property", "fb:app_id");
            $fb->addAttribute("content", $appId);

            return $this;
        }

        if (is_array($admins) && !empty($admins)) {
            foreach ($admins as $admin) {
                $fb = $this->meta->addChild("meta");
                $fb->addAttribute("property", "fb:admins");
                $fb->addAttribute("content", $admin);
            }
        }

        return $this;
    }
```

I'll try to make a PR soon.

**Comment by robsonvleite** [comment]
O problema aqui foi confundir os dados. Observando o método você deve informar um ou outro parâmetro e respeitar seus formatos.

->facebook("23434234") para APPID
OU
->facebook(null, ['394723943']) para 1 admin
OU
->facebook(null, ['394723943', ''219873892']) para admins

Coloquei uma verificação a mais no admins para validar o correto formato sem o erro. Agora se ocorrer o componente vai omitir a informação.
